### PR TITLE
Simplify compaction of apt-get calls

### PR DESCRIPTION
**Pull request by krlmlr**
Simpler regex, don't need to deal with `echo` when compacting.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Why not?

**Comment by krlmlr** [comment]
Because prepending `echo` now happens before compaction.

**Comment by gaborcsardi** [comment]
> Because prepending echo now happens before compaction.

Exactly, but that means that if you want to compact the `echo`-d commands, then you need to match `echo`, no?

**Comment by gaborcsardi** [comment]
Actually, it seems to me that `echo` is added _after_ compaction.

**Comment by krlmlr** [comment]
Yes, I was mistaken. With this PR:

- Getting the calls
- Compaction
- Adding `echo` 

Previously:

- Getting the calls
- Adding `echo` 
- Compaction

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
