### PR TITLE
Remove the source package after the package has been built

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by jimhester** [comment]
So the root cause of #159 seems to be we overwrite the original file with the built file path at https://github.com/r-lib/pkgdepends/pull/201/files#diff-165eec7c1940a41e1ba62bdf0fc3c5cbL524 and https://github.com/r-lib/pkgdepends/pull/201/files#diff-165eec7c1940a41e1ba62bdf0fc3c5cbL572.

One way to 'fix' this then is to unlink the old path before we overwrite it.

This means you need to re-run `x$download()` after running `x$install()`, but then the second install will work.

**Comment by jimhester** [comment]
@gaborcsardi do you think this is the best way to address this, or should we try a different approach?

**Comment by gaborcsardi** [comment]
> This means you need to re-run x$download() after running x$install(), but then the second install will work.

Hmmm, but it already works if you do that, I think?

Also, the tests that involve package building fail now, so maybe there is something wrong.

Btw. I am not sure that we need to fix this properly, it is not a very important use case, it is only annoying when testing pkgdepends interactively and an install fails. So we can just remove the downloads from the object, so you would need to re-download.

**Comment by jimhester** [comment]
It does not work with the current code if you re-download and then try to re-install.

I am fine just punting on this issue though, I agree it doesn't seem terribly important, but maybe we could improve the error message?

**Comment by gaborcsardi** [comment]
I don't think this is needed any more.

**Pull request closed without merging**
