### PR TITLE
Updating GitLab url parsing; fix authed list_refs

### LINKED ISSUE #328: Incorrect parse result of gitlab ref
``` r
pkgdepends::parse_pkg_ref("gitlab::https://foo.bar.com/aa/bb/cc")
#> $package
#> [1] "aa"
#> 
#> $protocol
#> [1] "https"
#> 
#> $host
#> [1] "foo.bar.co"
#> 
#> $username
#> [1] "m"
#> 
#> $repo
#> [1] "aa"
#> 
#> $subdir
#> [1] "bb/cc"
#> 
#> $commitish
#> [1] "HEAD"
#> 
#> $ref
#> [1] "gitlab::https://foo.bar.com/aa/bb/cc"
#> 
#> $path
#> [1] "/m/"
#> 
#> $dotgit
#> [1] ""
#> 
#> $url
#> [1] "https://foo.bar.co/m/aa.git"
#> 
#> $type
#> [1] "gitlab"
#> 
#> $params
#> character(0)
#> 
#> attr(,"class")
#> [1] "remote_ref_gitlab" "remote_ref"        "list"
```

<sup>Created on 2023-08-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Please have a look at `host` and `username` elements.

### PR DESCRIPTION
**Pull request by dgkf**
This PR is intended to fix #328 with a few other related fixes

* Updates parsing for GitLab remotes, which currently is forgetting a `/` between the host and "username". Unlike GitHub, GitLab allows arbitrary nesting of groups:
   | Service | Style |
   | --- | :-- |
   | GitHub | `username/repo` |
   | GitLab | `group/subgroup/subsubgroup/project` |
   
   This throws a wrench in the subdir parsing. To allow a subdir, I added a `/-/` separator:  
   `group/subgroup/project/-/sub/dir@ref`
   [`/-/` is a reserved name](https://docs.gitlab.com/ee/user/reserved_names.html) used for other server paths, so there's no risk of conflict with project paths. 
* Calls to `/info/refs?service=git-upload-pack` require authentication, which is currently ignored. I added this authentication to `async_git_list_refs_v2` and `async_git_send_message_v2`, necessary for solving package dependencies.

Let me know if I'm on the right track, or if you think this is better solved some other way.

### CODE REVIEW

**Comment by dgkf** [comment]
Since GitLab can have arbitrarily nested projects and some alternative syntax would be needed to differentiate `user/repo/sub/dir` from `/group/subgroup/subgroup2/subgroup3`, would an alternative syntax more akin to `Authors@R` be up for consideration?

```
Remotes:
  pkg=list(type = "gitlab", url = "https://acme.co/a/b/c.git", subdir = "x/y/z", ref = "dev")
```

I appreciate the emphasis on brevity, but maybe something more deterministic would be a nice fallback?

**Comment by gaborcsardi** [comment]
Thanks! I changed this a bit to add auth to all git HTTP queries. There is two things to do still:
- cache unsuccessful gitcreds queries, because they take about 0.2s now, and could take even longer with different git credential helpers,
- write tests.

**Comment by gaborcsardi** [comment]
> would an alternative syntax more akin to Authors@R be up for consideration?

That is not great, because other tools will interpret the `Remotes` field differently. It also does not play well with other, non-R tools that try to use the `DESCRIPTION` file.

> This throws a wrench in the subdir parsing. To allow a subdir, I added a /-/ separator: `group/subgroup/project/-/sub/dir@ref`

Yes, this could work.

**Comment by gaborcsardi** [comment]
Actually, some the git and gitlab tests are already "live", so we can update those later, and I am going to merge this now, after updating the docs.

**Comment by gaborcsardi** [comment]
Thanks you again!

**Pull request merged**
